# change the followings to match your Github username and repo name
baseurl: "/stefanTrawicki" # the name of your github repo
url: "https://stefanTrawicki.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Stefan Trawicki"
description: I’m Stefan, a machine learning and security researcher from the UK. I helped build Mindgard, and am also a PhD researcher at Lancaster University in both the Distributed Systems, and Security Lancaster groups.

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Stefan Trawicki
author-bio: Machine Learning and Security Researcher
author-image: stefan.png

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog.trawicki.io

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/stefanTrawicki/
linkedin: https://www.linkedin.com/in/stefan-trawicki/
medium: false
google-scholar: https://scholar.google.com/citations?user=XlAFln4AAAAJ&hl=en/
email: false

# footer information
footer-msg: ""
footer-msg-link: 

# google analytics
google-analytics: 

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
